version: "3.9"
services:
  dashboard-app:
    build: ./dashboard-app
    ports:
      - "8000:5000"
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER_FILE: run/secrets/db-user
      POSTGRES_PASSWORD_FILE: run/secrets/db-password
    secrets:
      - db-user
      - db-password
    ports:
      - "5432:5432"  
    volumes:
      - insight-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  db-fill:
    build: ./db-setup
    depends_on:
      postgres-db:
        condition: service_healthy

secrets:
  db-user:
    file: db-user.txt
  db-password:
    file: db-password.txt
  db-name:
    file: db-name.txt    

volumes:
  insight-postgres-data: